# Generated by Django 4.2.7 on 2023-12-16 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0003_alter_customuser_options_alter_customuser_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_subscribed',
            field=models.BooleanField(verbose_name='Підписан'),
        ),
    ]
