# Generated by Django 4.2.7 on 2023-12-21 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0005_alter_customuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(default=False, max_length=254, null=True, unique=True),
        ),
    ]
