# Generated by Django 4.2.7 on 2024-02-23 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0008_useraddresses'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraddresses',
            old_name='appartment_number',
            new_name='apartment_number',
        ),
        migrations.AlterField(
            model_name='useraddresses',
            name='delivery_method',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Метод доставки'),
        ),
    ]
