# Generated by Django 4.2.7 on 2023-12-04 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_rename_category_product_category_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='composition_en',
            field=models.TextField(blank=True, null=True, verbose_name='Склад (англійською)'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Опис (англійською)'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Назва (англійською)'),
        ),
        migrations.AddField(
            model_name='product',
            name='price_en',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Ціна (англійською)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.productcategory', verbose_name='Категорія'),
        ),
        migrations.AlterField(
            model_name='product',
            name='composition',
            field=models.TextField(verbose_name='Склад'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(verbose_name='Опис'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Назва'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ціна'),
        ),
    ]
