# Generated by Django 4.2.7 on 2023-12-05 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_product_composition_en_product_description_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategory',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Назва'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to='product_photos/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='sizequantity',
            name='quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='Кількість'),
        ),
        migrations.AlterField(
            model_name='sizequantity',
            name='size',
            field=models.CharField(choices=[('XS', 'Extra Small'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large')], max_length=2, verbose_name='Розмір'),
        ),
    ]
