# Generated by Django 4.2.7 on 2023-12-09 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_productcategory_name_alter_productimage_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Товар', 'verbose_name_plural': 'Додання товару'},
        ),
        migrations.AlterModelOptions(
            name='productcategory',
            options={'verbose_name': 'Категорiя', 'verbose_name_plural': 'Додання категорiй'},
        ),
    ]
