# Generated by Django 4.2.7 on 2024-01-11 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_alter_productimage_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sizequantity',
            name='size',
            field=models.CharField(choices=[('NS', 'No Size'), ('XS', 'Extra Small'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large')], max_length=2, verbose_name='Розмір'),
        ),
    ]
