# Generated by Django 4.2.7 on 2024-01-11 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_alter_sizequantity_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Опубліковано'),
        ),
        migrations.AlterField(
            model_name='sizequantity',
            name='size',
            field=models.CharField(choices=[('NS', 'No Size'), ('XS', 'Extra Small'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large')], default='NS', max_length=2, verbose_name='Розмір'),
        ),
    ]
