# Generated by Django 4.2.7 on 2024-01-13 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_product_is_active_alter_sizequantity_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(blank=True, max_length=255, null=True, verbose_name="Ім'я категорії")),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Назва')),
                ('name_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Назва (англійською)')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Ціна')),
                ('price_en', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Ціна (англійською)')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Опис')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='Опис (англійською)')),
                ('composition', models.TextField(blank=True, null=True, verbose_name='Склад')),
                ('composition_en', models.TextField(blank=True, null=True, verbose_name='Склад (англійською)')),
                ('size', models.CharField(max_length=2, verbose_name='Розмір')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Кількість')),
                ('category_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.productcategory', verbose_name='Категорія')),
            ],
        ),
    ]
