# Generated by Django 4.2.7 on 2024-01-25 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_productorder_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Показ товару на головній сторінці', verbose_name='Опубліковано'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_en',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Ціна в $', max_digits=10, null=True, verbose_name='Ціна (англійською)'),
        ),
        migrations.AlterField(
            model_name='sizequantity',
            name='quantity',
            field=models.PositiveIntegerField(default=0, help_text='ОБОВЯЗКОВЕ ПОЛЕ!!! Якщо товар не має кіл-сті, оберіть будь-яке значення більше 0. Товар автоматично виключаеться коли кіл-сть дорівнює 0', verbose_name='Кількість'),
        ),
        migrations.AlterField(
            model_name='sizequantity',
            name='size',
            field=models.CharField(choices=[('NS', 'No Size'), ('XS', 'Extra Small'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large')], default='NS', help_text="ОБОВЯЗКОВЕ ПОЛЕ!!! Якщо товар не має розміру, оберіть розмір 'No Size'.", max_length=2, verbose_name='Розмір'),
        ),
    ]
