# Generated by Django 4.2.7 on 2024-01-04 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_remove_cart_items_cart_product_cart_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='session_id',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
    ]
