# Generated by Django 4.2.7 on 2024-01-13 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_alter_cart_session_id'),
        ('cart', '0010_alter_cart_order'),
    ]

    operations = [
    ]
