# Generated by Django 4.2.7 on 2023-12-14 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailsubscribers',
            name='subscribed',
        ),
        migrations.AddField(
            model_name='emailsubscribers',
            name='is_subscribed',
            field=models.BooleanField(default=False),
        ),
    ]
