# Generated by Django 4.2.7 on 2024-01-09 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_remove_cart_uuid_cart_product_cart_quantity_and_more'),
        ('orders', '0007_alter_order_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.AddField(
            model_name='order',
            name='carts',
            field=models.ManyToManyField(blank=True, to='cart.cart', verbose_name='Корзіни'),
        ),
    ]
