# Generated by Django 4.2.7 on 2024-01-09 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_alter_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='carts',
        ),
    ]
