# Generated by Django 4.2.7 on 2024-01-25 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_order_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Новий', 'Новий'), ('Прийнято', 'Прийнято'), ('Скасовано', 'Скасовано'), ('Оплачено', 'Оплачено'), ('В дорозі', 'В дорозі'), ('Виконано', 'Виконано')], default='Новий', max_length=20, verbose_name='Статус'),
        ),
    ]
