# Generated by Django 4.2.7 on 2024-02-23 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_remove_order_city_remove_order_country_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='user_address',
        ),
        migrations.AddField(
            model_name='order',
            name='apartment_number',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Номер квартири'),
        ),
        migrations.AddField(
            model_name='order',
            name='city',
            field=models.CharField(default='', max_length=50, verbose_name='Місто'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='country',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Країна'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_method',
            field=models.CharField(default='', max_length=50, verbose_name='Метод доставки'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Відділення'),
        ),
        migrations.AddField(
            model_name='order',
            name='email',
            field=models.EmailField(default='test', max_length=40, verbose_name='Пошта'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='first_name',
            field=models.CharField(default='', max_length=50, verbose_name="Ім'я"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='house_number',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Номер будинку'),
        ),
        migrations.AddField(
            model_name='order',
            name='last_name',
            field=models.CharField(default='', max_length=50, verbose_name='Прізвище'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.CharField(default='phone', max_length=15, verbose_name='Телефон'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='state',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Область'),
        ),
        migrations.AddField(
            model_name='order',
            name='street',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Вулиця'),
        ),
        migrations.AddField(
            model_name='order',
            name='zip_code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Поштовий індекс'),
        ),
    ]
